### ISSUE TITLE
[ALIASES] Remove tooltip from Datasets view on hover over dataset name

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#134] opened 2017-03-06 17:05 UTC
When hovering on a dataset name, a tooltip containing the name of the dataset will appear. It must be removed. See screenshot:

![screenshot from 2017-03-06 11-54-23](https://cloud.githubusercontent.com/assets/4222826/23620502/670f296a-0297-11e7-91eb-914f7c39bdbe.png)

**Comment by coyle5280** [comment] 2017-03-06 21:41
I am not able to reproduce this bug but I think I have a fix but am unable to test it.

**Comment by gfiorav** [comment] 2017-03-07 16:14
Do you have a branch so that I can test it?

**Comment by coyle5280** [comment] 2017-03-07 16:23
The branch with the code is 134_remove_tooltip_datasets

**Comment by gfiorav** [comment] 2017-03-07 17:53
From our research:

It seems that what causes the tooltip is the `title` attribute on `<a>` tags. Removing these attributes from the datasets and maps dashboards should be enough :)

Thanks!

**Comment by coyle5280** [comment] 2017-03-07 18:58
This will be closed by PR #141 

Please review PR #141 and let me know if there are any questions.

Thanks

**Closed as completed** 2017-03-09 17:47 UTC
